31719     
Delivered-To: norberto@10gen.com
Received: by 10.60.24.70 with SMTP id s6csp238648oef;
        Thu, 6 Sep 2012 15:24:07 -0700 (PDT)
Received: by 10.59.5.73 with SMTP id ck9mr5030388ved.22.1346970247474;
        Thu, 06 Sep 2012 15:24:07 -0700 (PDT)
Return-Path: <mongodb-user+bncCKej7qzPFhCFxaSCBRoEwb9TNw@googlegroups.com>
Received: from mail-vb0-f58.google.com (mail-vb0-f58.google.com [209.85.212.58])
        by mx.google.com with ESMTPS id ul10si3226014vec.2.2012.09.06.15.24.07
        (version=TLSv1/SSLv3 cipher=OTHER);
        Thu, 06 Sep 2012 15:24:07 -0700 (PDT)
Received-SPF: pass (google.com: domain of mongodb-user+bncCKej7qzPFhCFxaSCBRoEwb9TNw@googlegroups.com designates 209.85.212.58 as permitted sender) client-ip=209.85.212.58;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of mongodb-user+bncCKej7qzPFhCFxaSCBRoEwb9TNw@googlegroups.com designates 209.85.212.58 as permitted sender) smtp.mail=mongodb-user+bncCKej7qzPFhCFxaSCBRoEwb9TNw@googlegroups.com; dkim=pass header.i=@googlegroups.com
Received: by vbme21 with SMTP id e21sf1623698vbm.23
        for <multiple recipients>; Thu, 06 Sep 2012 15:24:07 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=googlegroups.com; s=20120806;
        h=x-beenthere:received-spf:mime-version:in-reply-to:references:from
         :date:message-id:subject:to:x-original-sender
         :x-original-authentication-results:reply-to:precedence:mailing-list
         :list-id:x-google-group-id:list-post:list-help:list-archive:sender
         :list-subscribe:list-unsubscribe:content-type;
        bh=PGcPJ+nxu3D/TvducCdOrXKSAWKLmGgXIkiwu+ksx/g=;
        b=MfTOwTBZcGSUZBg4RZjKAo4GIOQFWIKbTpsyRqJ4sVaK6BZ/6yoVW2+cFUkr3P5zTK
         BTtBFsbLvOFwzAVf7CcXeUCMxKGQs9Fthjuq5Ip4fM70Z8ILb0voAx8EjltzBpfPFjAj
         G1pqpVjJ8A96OrV/xQvbZt4aC0Nb2cqUHAU4TQ7qXQ5yEEblJkL9PlFWEiAxlFEs3CqK
         7FiNKxMBF1FSn6AzHyp0Z33iXsK7vtEZbI/rWqiVfBbO29sVm0CyBqhFyad8CnU0S5Y2
         a3jxw/SR4yH8ARBm8o020DI57OXSH99AZuGa6TNbp++HBood5dN8hVGcSal0Tp34oz18
         VLUg==
Received: by 10.50.77.200 with SMTP id u8mr10809598igw.3.1346970246813;
        Thu, 06 Sep 2012 15:24:06 -0700 (PDT)
X-BeenThere: mongodb-user@googlegroups.com
Received: by 10.50.157.164 with SMTP id wn4ls53067igb.0.canary; Thu, 06 Sep
 2012 15:24:04 -0700 (PDT)
Received: by 10.42.54.66 with SMTP id q2mr1728974icg.17.1346970244655;
        Thu, 06 Sep 2012 15:24:04 -0700 (PDT)
Received: by 10.42.54.66 with SMTP id q2mr1728973icg.17.1346970244632;
        Thu, 06 Sep 2012 15:24:04 -0700 (PDT)
Received: from mail-iy0-f170.google.com (mail-iy0-f170.google.com [209.85.210.170])
        by gmr-mx.google.com with ESMTPS id xd1si1328287igb.1.2012.09.06.15.24.04
        (version=TLSv1/SSLv3 cipher=OTHER);
        Thu, 06 Sep 2012 15:24:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of puentesarrin@gmail.com designates 209.85.210.170 as permitted sender) client-ip=209.85.210.170;
Received: by iamm10 with SMTP id m10so2233740iam.15
        for <mongodb-user@googlegroups.com>; Thu, 06 Sep 2012 15:24:04 -0700 (PDT)
Received: by 10.50.195.169 with SMTP id if9mr5201567igc.62.1346970244208; Thu,
 06 Sep 2012 15:24:04 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.64.102.72 with HTTP; Thu, 6 Sep 2012 15:23:23 -0700 (PDT)
In-Reply-To: <916848a6-8582-4bf6-8f29-dabc638163e9@googlegroups.com>
References: <CAO+R_P8=wzh5kbPU2-Hv=2i_sdYp6Jm+phxh+qLSN8n1VqTi_w@mail.gmail.com>
 <CAO+R_P_FfM8Fx=6OjQRHFue07fuqxdLHc+OEkBQtnVPhERYf6g@mail.gmail.com>
 <d0d1eb71-33d7-4004-b4c9-90c4e76fe6ef@googlegroups.com> <CAO+R_P9VpVUVLPMe=yCLk7EaLuC5YgfZmxJTjBTckro4BUQQ+Q@mail.gmail.com>
 <916848a6-8582-4bf6-8f29-dabc638163e9@googlegroups.com>
From: =?ISO-8859-1?Q?Jorge_Puente_Sarr=EDn?= <puentesarrin@gmail.com>
Date: Thu, 6 Sep 2012 17:23:23 -0500
Message-ID: <CAO+R_P84Chiamc03DBKWfbcP8Y3e3HMzHOYBt4rC-EEOLKrQ+w@mail.gmail.com>
Subject: Re: [mongodb-user] Re: [pymongo-motor] OperationFailure on insert
To: mongodb-user@googlegroups.com
X-Original-Sender: puentesarrin@gmail.com
X-Original-Authentication-Results: gmr-mx.google.com; spf=pass (google.com:
 domain of puentesarrin@gmail.com designates 209.85.210.170 as permitted
 sender) smtp.mail=puentesarrin@gmail.com; dkim=pass header.i=@gmail.com
Reply-To: mongodb-user@googlegroups.com
Precedence: list
Mailing-list: list mongodb-user@googlegroups.com; contact mongodb-user+owners@googlegroups.com
List-ID: <mongodb-user.googlegroups.com>
X-Google-Group-Id: 1044811755470
List-Post: <http://groups.google.com/group/mongodb-user/post?hl=en_US>, <mailto:mongodb-user@googlegroups.com>
List-Help: <http://groups.google.com/support/?hl=en_US>, <mailto:mongodb-user+help@googlegroups.com>
List-Archive: <http://groups.google.com/group/mongodb-user?hl=en_US>
Sender: mongodb-user@googlegroups.com
List-Subscribe: <http://groups.google.com/group/mongodb-user/subscribe?hl=en_US>,
 <mailto:mongodb-user+subscribe@googlegroups.com>
List-Unsubscribe: <http://groups.google.com/group/mongodb-user/subscribe?hl=en_US>,
 <mailto:googlegroups-manage+1044811755470+unsubscribe@googlegroups.com>
Content-Type: multipart/alternative; boundary=14dae9340469edd79904c90ff247

--14dae9340469edd79904c90ff247
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

No, that's not working.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line
306, in insert
    continue_on_error, self.__uuid_subtype), safe)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/connection.py", line
745, in _send_message
    rv =3D self.__check_response_to_last_error(response)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/connection.py", line
681, in __check_response_to_last_error
    helpers._check_command_response(error, self.disconnect)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line
129, in _check_command_response
    raise OperationFailure(msg % response["errmsg"])
pymongo.errors.OperationFailure: need to login

Then, what's the best way for work with a MongoDB Uri and authenticate?

def connect(user, pass):
     yield motor.Op(db.authenticate, user, pass)



2012/9/6 A. Jesse Jiryu Davis <jesse@10gen.com>

> I see. Does that work with a regular PyMongo Connection?:
>
> db =3D pymongo.Connection('**mongodb://user:pass@xxxxx.**mongolab.com:
> xxxxx/dbname?**safe=3Dtrue').dbname
> db.my_collection.insert({}, safe=3DTrue)
>
>
> On Thursday, September 6, 2012 6:02:36 PM UTC-4, Jorge Puente Sarr=EDn wr=
ote:
>
>> Hi Jesse,
>>
>> I have tried to run your snippet and I think that the problem is
>> Connection, because for create it, I'm using a Uri such as:
>>
>> db =3D motor.MotorConnection('**mongodb://user:pass@xxxxx.**mongolab.com=
:
>> xxxxx/dbname?**safe=3Dtrue').open_sync().dbname
>>
>> This is the traceback,
>>
>> ERROR:root:Exception in callback <tornado.stack_context._**StackContextW=
rapper
>> object at 0x7fc5af09bd08>
>> Traceback (most recent call last):
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/ioloop.**py",
>> line 421, in _run_callback
>>     callback()
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/stack_**context=
.py",
>> line 229, in wrapped
>>     callback(*args, **kwargs)
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/gen.py", line
>> 382, in inner
>>     self.set_result(key, result)
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/gen.py", line
>> 315, in set_result
>>     self.run()
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/gen.py", line
>> 343, in run
>>     yielded =3D self.gen.throw(*exc_info)
>>   File "<stdin>", line 4, in go
>>   File "/usr/local/lib/python2.7/**dist-packages/tornado/gen.py", line
>> 335, in run
>>     next =3D self.yield_point.get_result()
>>   File "/usr/local/lib/python2.7/**dist-packages/motor/__init__.**py",
>> line 1365, in get_result
>>     raise error
>> OperationFailure: db assertion failure, assertion: 'unauthorized
>> db:my_database ns:my_database lock type:1 client:190.41.238.178',
>> assertionCode: 10057
>>
>> Does PyMongo invoke to authenticate method when a uri have a
>> user/password? Or Does PyMongo ignored it, when uri have a db name?
>>
>> 2012/9/6 A. Jesse Jiryu Davis <je...@10gen.com>
>>
>>> In that case it seems that you are, perhaps, logged in as a read-only
>>> user, and you're mistaken that your document was correctly inserted? Tr=
y
>>> this:
>>>
>>> import datetime
>>> from tornado.ioloop import IOLoop
>>> from tornado import gen
>>> import motor
>>>
>>> db =3D motor.MotorConnection().open_**sync().my_database
>>> loop =3D IOLoop.instance()
>>>
>>> @gen.engine
>>> def go():
>>>     print 'dropping my_collection'
>>>     yield motor.Op(db.drop_collection, 'my_collection')
>>>     count =3D yield motor.Op(db.my_collection.**count)
>>>     print 'count is', count
>>>
>>>     content =3D {'title': 'title',
>>>                'content': 'content',
>>>                'slug': 'slug',
>>>                'date': datetime.datetime.now()}
>>>     yield motor.Op(db.my_collection.**insert, content)
>>>     count =3D yield motor.Op(db.my_collection.**count)
>>>     print 'count is', count
>>>     loop.stop()
>>>
>>> go()
>>> loop.start()
>>>
>>> Replace "my_database" with the database you're using, and run this
>>> script, please. Be aware that this script drops a collection called
>>> "my_collection."
>>>
>>> On Thursday, September 6, 2012 3:57:53 PM UTC-4, Jorge Puente Sarr=EDn
>>> wrote:
>>>
>>>> I have reviewed the DB and the document is inserted correctly, but I
>>>> don't understand why raise this exception.
>>>>
>>>> Regards.
>>>>
>>>> 2012/9/6 Jorge Puente Sarr=EDn <puente...@gmail.com>
>>>>
>>>> Hi, I'm following the Motor examples<http://emptysquare.net/motor/pymo=
ngo/api/motor/examples.html#using-tornado-s-generator-interface>,
>>>>> but my code raise a exception when insert a document using yield oper=
ator
>>>>> and motor Op/Task.
>>>>>
>>>>> Here my code:
>>>>>
>>>>> class ContentHandler(**MotorSampleHand**ler):
>>>>>
>>>>>      @tornado.web.asynchronous
>>>>>     @tornado.gen.engine
>>>>>     def post(self):
>>>>>         title =3D self.get_argument('title')
>>>>>         slug =3D stringhelper.get_slug(title)
>>>>>         content =3D {'title': title,
>>>>>             'content': self.get_argument('content'),
>>>>>             'slug': slug,
>>>>>             'date': datetime.datetime.now()}
>>>>>         *yield motor.Op(self.db.contents.insert, content)*
>>>>>         self.redirect('/%s' % slug)
>>>>>
>>>>> This is the traceback:
>>>>>
>>>>>     Traceback (most recent call last):
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/web.py=
",
>>>>> line 1000, in _stack_context_handle_**exceptio**n
>>>>>         raise_exc_info((type, value, traceback))
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/stack_=
*
>>>>> *contex**t.py", line 256, in _nested
>>>>>         yield vars
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/stack_=
*
>>>>> *contex**t.py", line 226, in wrapped
>>>>>         callback(*args, **kwargs)
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/gen.py=
",
>>>>> line 382, in inner
>>>>>         self.set_result(key, result)
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/gen.py=
",
>>>>> line 315, in set_result
>>>>>         self.run()
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/gen.py=
",
>>>>> line 343, in run
>>>>>         yielded =3D self.gen.throw(*exc_info)
>>>>> *      File "/home/puentesarrin/projects/motor-sample/motor-sample/
>>>>> handlers.py", line 111, in post*
>>>>> *        yield motor.Op(self.db.contents.insert, content)*
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/tornado/gen.py=
",
>>>>> line 335, in run
>>>>>         next =3D self.yield_point.get_result()
>>>>>       File "/usr/local/lib/python2.7/**dist**-packages/motor/__init__=
.
>>>>> **py", line 1365, in get_result
>>>>>         raise error
>>>>>     OperationFailure: need to login
>>>>>
>>>>> I think that it's not about instance PyMongo Connection because, all
>>>>> of queries (find/find_one) results is ok.
>>>>>
>>>>> Python version: 2.7.3
>>>>> Tornado version: 2.3
>>>>> PyMongo version: 2.2
>>>>>
>>>>> --
>>>>> Atte.
>>>>> Jorge Puente Sarr=EDn.
>>>>>
>>>>
>>>>
>>>>
>>>> --
>>>> Atte.
>>>> Jorge Puente Sarr=EDn.
>>>>
>>>  --
>>> You received this message because you are subscribed to the Google
>>> Groups "mongodb-user" group.
>>> To post to this group, send email to mongod...@googlegroups.com
>>>
>>> To unsubscribe from this group, send email to
>>> mongodb-user...@**googlegroups.com
>>>
>>> See also the IRC channel -- freenode.net#mongodb
>>>
>>
>>
>>
>> --
>> Atte.
>> Jorge Puente Sarr=EDn.
>>
>  --
> You received this message because you are subscribed to the Google
> Groups "mongodb-user" group.
> To post to this group, send email to mongodb-user@googlegroups.com
> To unsubscribe from this group, send email to
> mongodb-user+unsubscribe@googlegroups.com
> See also the IRC channel -- freenode.net#mongodb
>



--=20
Atte.
Jorge Puente Sarr=EDn.

--=20
You received this message because you are subscribed to the Google
Groups "mongodb-user" group.
To post to this group, send email to mongodb-user@googlegroups.com
To unsubscribe from this group, send email to
mongodb-user+unsubscribe@googlegroups.com
See also the IRC channel -- freenode.net#mongodb

--14dae9340469edd79904c90ff247
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable

<div>No, that&#39;s not working.</div><div><br></div><div><font face=3D"&#3=
9;courier new&#39;, monospace">Traceback (most recent call last):</font></d=
iv><div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;&lt;=
stdin&gt;&quot;, line 1, in &lt;module&gt;</font></div>

<div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;/usr/lo=
cal/lib/python2.7/dist-packages/pymongo/collection.py&quot;, line 306, in i=
nsert</font></div><div><font face=3D"&#39;courier new&#39;, monospace">=A0 =
=A0 continue_on_error, self.__uuid_subtype), safe)</font></div>

<div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;/usr/lo=
cal/lib/python2.7/dist-packages/pymongo/connection.py&quot;, line 745, in _=
send_message</font></div><div><font face=3D"&#39;courier new&#39;, monospac=
e">=A0 =A0 rv =3D self.__check_response_to_last_error(response)</font></div=
>

<div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;/usr/lo=
cal/lib/python2.7/dist-packages/pymongo/connection.py&quot;, line 681, in _=
_check_response_to_last_error</font></div><div><font face=3D"&#39;courier n=
ew&#39;, monospace">=A0 =A0 helpers._check_command_response(error, self.dis=
connect)</font></div>

<div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;/usr/lo=
cal/lib/python2.7/dist-packages/pymongo/helpers.py&quot;, line 129, in _che=
ck_command_response</font></div><div><font face=3D"&#39;courier new&#39;, m=
onospace">=A0 =A0 raise OperationFailure(msg % response[&quot;errmsg&quot;]=
)</font></div>

<div><font face=3D"&#39;courier new&#39;, monospace">pymongo.errors.Operati=
onFailure: need to login</font></div><div><br></div><div>Then, what&#39;s t=
he best way for work with a MongoDB Uri and authenticate?=A0</div><div><br>

</div><div><div><font face=3D"&#39;courier new&#39;, monospace">def connect=
(user, pass):</font></div><div><font face=3D"&#39;courier new&#39;, monospa=
ce">=A0 =A0 =A0yield motor.Op(db.authenticate, user, pass)</font></div></di=
v><div>

<br></div><div><br></div><br><div class=3D"gmail_quote">2012/9/6 A. Jesse J=
iryu Davis <span dir=3D"ltr">&lt;<a href=3D"mailto:jesse@10gen.com" target=
=3D"_blank">jesse@10gen.com</a>&gt;</span><br><blockquote class=3D"gmail_qu=
ote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex=
">

I see. Does that work with a regular PyMongo Connection?:<div><br></div><di=
v><span style=3D"font-family:&#39;courier new&#39;,monospace">db =3D pymong=
o.Connection(&#39;</span><u></u><span style=3D"font-family:&#39;courier new=
&#39;,monospace">mongodb://user:pass@xxxxx.</span><u></u><span style=3D"fon=
t-family:&#39;courier new&#39;,monospace">mongolab.com:xxxxx/dbname?</span>=
<u></u><span style=3D"font-family:&#39;courier new&#39;,monospace">safe=3Dt=
rue&#39;).dbname</span></div>

<div><font face=3D"courier new, monospace">db.my_collection.insert({}, safe=
=3DTrue)</font></div><div><div class=3D"im"><font face=3D"courier new, mono=
space"><br></font><br>On Thursday, September 6, 2012 6:02:36 PM UTC-4, Jorg=
e Puente Sarr=EDn wrote:</div>

<blockquote class=3D"gmail_quote" style=3D"margin:0;margin-left:0.8ex;borde=
r-left:1px #ccc solid;padding-left:1ex"><div class=3D"im"><div>Hi Jesse,</d=
iv><div><br>I have tried to run your snippet and I think that the problem i=
s Connection, because for create it, I&#39;m using a Uri such as:</div>

<div><br></div><div><span style=3D"font-family:&#39;courier new&#39;,monosp=
ace">db =3D motor.MotorConnection(&#39;<u></u>mongodb://user:pass@xxxxx.<u>=
</u>mongolab.com:xxxxx/dbname?<u></u>safe=3Dtrue&#39;).open_sync().dbname</=
span></div>



<div><br></div><div>This is the traceback,</div><div><br></div><div><div><f=
ont face=3D"&#39;courier new&#39;, monospace">ERROR:root:Exception in callb=
ack &lt;tornado.stack_context._<u></u>StackContextWrapper object at 0x7fc5a=
f09bd08&gt;</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">Traceback (most recent=
 call last):</font></div><div><font face=3D"&#39;courier new&#39;, monospac=
e">=A0 File &quot;/usr/local/lib/python2.7/<u></u>dist-packages/tornado/iol=
oop.<u></u>py&quot;, line 421, in _run_callback</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 callback()</fo=
nt></div><div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quo=
t;/usr/local/lib/python2.7/<u></u>dist-packages/tornado/stack_<u></u>contex=
t.py&quot;, line 229, in wrapped</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 callback(*args=
, **kwargs)</font></div><div><font face=3D"&#39;courier new&#39;, monospace=
">=A0 File &quot;/usr/local/lib/python2.7/<u></u>dist-packages/tornado/gen.=
py&quot;, line 382, in inner</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 self.set_resul=
t(key, result)</font></div><div><font face=3D"&#39;courier new&#39;, monosp=
ace">=A0 File &quot;/usr/local/lib/python2.7/<u></u>dist-packages/tornado/g=
en.py&quot;, line 315, in set_result</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 self.run()</fo=
nt></div><div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quo=
t;/usr/local/lib/python2.7/<u></u>dist-packages/tornado/gen.py&quot;, line =
343, in run</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 yielded =3D se=
lf.gen.throw(*exc_info)</font></div><div><font face=3D"&#39;courier new&#39=
;, monospace">=A0 File &quot;&lt;stdin&gt;&quot;, line 4, in go</font></div=
><div><font face=3D"&#39;courier new&#39;, monospace">=A0 File &quot;/usr/l=
ocal/lib/python2.7/<u></u>dist-packages/tornado/gen.py&quot;, line 335, in =
run</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 next =3D self.=
yield_point.get_result()</font></div><div><font face=3D"&#39;courier new&#3=
9;, monospace">=A0 File &quot;/usr/local/lib/python2.7/<u></u>dist-packages=
/motor/__init__.<u></u>py&quot;, line 1365, in get_result</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 raise error</f=
ont></div><div><font face=3D"&#39;courier new&#39;, monospace">OperationFai=
lure: db assertion failure, assertion: &#39;unauthorized db:my_database ns:=
my_database lock type:1 client:190.41.238.178&#39;, assertionCode: 10057</f=
ont></div>



</div><div><br></div>Does PyMongo invoke to=A0<font face=3D"&#39;courier ne=
w&#39;, monospace">authenticate</font>=A0method when a uri have a user/pass=
word? Or Does PyMongo ignored it, when uri have a db name?<br><br></div><di=
v class=3D"gmail_quote">



2012/9/6 A. Jesse Jiryu Davis <span dir=3D"ltr">&lt;<a>je...@10gen.com</a>&=
gt;</span><br><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;=
border-left:1px #ccc solid;padding-left:1ex"><div><div class=3D"h5">

In that case it seems that you are, perhaps, logged in as a read-only user,=
 and you&#39;re mistaken that your document was correctly inserted? Try thi=
s:<div><br></div><div><div><font face=3D"courier new, monospace">import dat=
etime</font></div>



<div><font face=3D"courier new, monospace">from tornado.ioloop import IOLoo=
p</font></div><div><font face=3D"courier new, monospace">from tornado impor=
t gen</font></div><div><font face=3D"courier new, monospace">import motor</=
font></div>



<div><font face=3D"courier new, monospace"><br></font></div><div><font face=
=3D"courier new, monospace">db =3D motor.MotorConnection().open_<u></u>sync=
().my_database</font></div><div><font face=3D"courier new, monospace">loop =
=3D IOLoop.instance()</font></div>



<div><font face=3D"courier new, monospace"><br></font></div><div><font face=
=3D"courier new, monospace">@gen.engine</font></div><div><font face=3D"cour=
ier new, monospace">def go():</font></div><div><font face=3D"courier new, m=
onospace">=A0 =A0 print &#39;dropping my_collection&#39;</font></div>



<div><font face=3D"courier new, monospace">=A0 =A0 yield motor.Op(db.drop_c=
ollection, &#39;my_collection&#39;)</font></div><div><font face=3D"courier =
new, monospace">=A0 =A0 count =3D yield motor.Op(db.my_collection.<u></u>co=
unt)</font></div>



<div><font face=3D"courier new, monospace">=A0 =A0 print &#39;count is&#39;=
, count</font></div><div><font face=3D"courier new, monospace"><br></font><=
/div><div><font face=3D"courier new, monospace">=A0 =A0 content =3D {&#39;t=
itle&#39;: &#39;title&#39;,</font></div>



<div><font face=3D"courier new, monospace">=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0&=
#39;content&#39;: &#39;content&#39;,</font></div><div><font face=3D"courier=
 new, monospace">=A0 =A0 =A0 =A0 =A0 =A0 =A0 =A0&#39;slug&#39;: &#39;slug&#=
39;,</font></div><div><font face=3D"courier new, monospace">=A0 =A0 =A0 =A0=
 =A0 =A0 =A0 =A0&#39;date&#39;: datetime.datetime.now()}</font></div>



<div><font face=3D"courier new, monospace">=A0 =A0 yield motor.Op(db.my_col=
lection.<u></u>insert, content)</font></div><div><font face=3D"courier new,=
 monospace">=A0 =A0 count =3D yield motor.Op(db.my_collection.<u></u>count)=
</font></div>

<div><font face=3D"courier new, monospace">=A0 =A0 print &#39;count is&#39;=
, count</font></div>

<div><font face=3D"courier new, monospace">=A0 =A0 loop.stop()</font></div>=
<div><font face=3D"courier new, monospace"><br></font></div><div><font face=
=3D"courier new, monospace">go()</font></div><div><font face=3D"courier new=
, monospace">loop.start()</font></div>



<div><br></div><div>Replace &quot;my_database&quot; with the database you&#=
39;re using, and run this script, please. Be aware that this script drops a=
 collection called &quot;my_collection.&quot;</div><div><br>

On Thursday, September 6, 2012 3:57:53 PM UTC-4, Jorge Puente Sarr=EDn wrot=
e:</div><blockquote class=3D"gmail_quote" style=3D"margin:0;margin-left:0.8=
ex;border-left:1px #ccc solid;padding-left:1ex"><div>I have reviewed the DB=
 and the document is inserted correctly, but I don&#39;t understand why rai=
se this exception.<div>



<br></div></div><div>Regards.<br><br><div class=3D"gmail_quote">2012/9/6 Jo=
rge Puente Sarr=EDn <span dir=3D"ltr">&lt;<a>puente...@gmail.com</a>&gt;</s=
pan><div><div><br>


<blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1p=
x #ccc solid;padding-left:1ex">Hi, I&#39;m following the=A0<a href=3D"http:=
//emptysquare.net/motor/pymongo/api/motor/examples.html#using-tornado-s-gen=
erator-interface" target=3D"_blank">Motor examples</a>, but my code raise a=
 exception when insert a document using yield operator and motor Op/Task.<d=
iv>







<br></div><div>Here my code:</div><div><br></div><div><div><font face=3D"&#=
39;courier new&#39;, monospace">class ContentHandler(<u></u>MotorSampleHand=
<u></u>ler):</font></div><div><font face=3D"&#39;courier new&#39;, monospac=
e"><br>



</font></div>



<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 @tornado.web.a=
synchronous</font></div><div><font face=3D"&#39;courier new&#39;, monospace=
">=A0 =A0 @tornado.gen.engine</font></div><div><font face=3D"&#39;courier n=
ew&#39;, monospace">=A0 =A0 def post(self):</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0=A0</fo=
nt><span style=3D"font-family:&#39;courier new&#39;,monospace">title =3D=A0=
</span><span style=3D"font-family:&#39;courier new&#39;,monospace">self.get=
_argument(&#39;title&#39;)</span></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 slug =
=3D stringhelper.get_slug(title)</font></div><div><font face=3D"&#39;courie=
r new&#39;, monospace">=A0 =A0 =A0 =A0 content =3D {&#39;title&#39;: title,=
</font></div><div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =
=A0 =A0 =A0 =A0 &#39;</font><span style=3D"font-family:&#39;courier new&#39=
;,monospace">content&#39;: self.get_argument(&#39;content&#39;),</span></di=
v>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 =A0 =
=A0 &#39;slug&#39;: slug,</font></div><div><font face=3D"&#39;courier new&#=
39;, monospace">=A0 =A0 =A0 =A0 =A0 =A0 &#39;date&#39;: datetime.datetime.n=
ow()}</font></div><div><font face=3D"&#39;courier new&#39;, monospace">=A0 =
=A0 =A0 =A0=A0</font><span style=3D"font-family:&#39;courier new&#39;,monos=
pace"><b>yield motor.Op(self.db.contents.<u></u>inse<u></u>rt, content)</b>=
</span></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 self.r=
edirect(&#39;/%s&#39; % slug)</font></div></div><div><br></div><div>This is=
 the traceback:<br clear=3D"all"><div><br></div><div><div><font face=3D"&#3=
9;courier new&#39;, monospace">=A0 =A0 Traceback (most recent call last):</=
font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/web.py&quot;,=
 line 1000, in _stack_context_handle_<u></u>exceptio<u></u>n</font></div><d=
iv>

<font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 raise_exc_i=
nfo((type, value, traceback))</font></div>





<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/stack_<u></u>=
contex<u></u>t.py&quot;, line 256, in _nested</font></div><div><font face=
=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 yield vars</font></di=
v>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/stack_<u></u>=
contex<u></u>t.py&quot;, line 226, in wrapped</font></div><div><font face=
=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 =A0 callback(*args, **kwa=
rgs)</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/gen.py&quot;,=
 line 382, in inner</font></div><div><font face=3D"&#39;courier new&#39;, m=
onospace">=A0 =A0 =A0 =A0 self.set_result(key, result)</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/gen.py&quot;,=
 line 315, in set_result</font></div><div><font face=3D"&#39;courier new&#3=
9;, monospace">=A0 =A0 =A0 =A0 self.run()</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/gen.py&quot;,=
 line 343, in run</font></div><div><font face=3D"&#39;courier new&#39;, mon=
ospace">=A0 =A0 =A0 =A0 yielded =3D self.gen.throw(*exc_info)</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace"><b>=A0 =A0 =A0 File &q=
uot;/home/puentesarrin/projects/<u></u>m<u></u>otor-sample/motor-sample/<u>=
</u>handl<u></u>ers.py&quot;, line 111, in post</b></font></div><div><font =
face=3D"&#39;courier new&#39;, monospace"><b>=A0 =A0 =A0 =A0 yield motor.Op=
(self.db.contents.<u></u>inse<u></u>rt, content)</b></font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/tornado/gen.py&quot;,=
 line 335, in run</font></div><div><font face=3D"&#39;courier new&#39;, mon=
ospace">=A0 =A0 =A0 =A0 next =3D self.yield_point.get_result()</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 =A0 File &quot=
;/usr/local/lib/python2.7/<u></u>dist<u></u>-packages/motor/__init__.<u></u=
>py&quot;, line 1365, in get_result</font></div><div><font face=3D"&#39;cou=
rier new&#39;, monospace">=A0 =A0 =A0 =A0 raise error</font></div>







<div><font face=3D"&#39;courier new&#39;, monospace">=A0 =A0 OperationFailu=
re: need to login</font></div></div><div><br></div><div>I think that it&#39=
;s not about instance PyMongo Connection because, all of queries (find/find=
_one) results is ok.</div>







<div><br></div><div>Python version: 2.7.3</div><div>Tornado version: 2.3</d=
iv><div>PyMongo version: 2.2</div><span><font color=3D"#888888"><div><br></=
div>-- <br>Atte.<br>Jorge Puente Sarr=EDn.<br>
</font></span></div>
</blockquote></div></div></div><div><div><br><br clear=3D"all"><div><br></d=
iv>-- <br>Atte.<br>Jorge Puente Sarr=EDn.<br>
</div></div></div><span><font color=3D"#888888">
</font></span></blockquote></div></div></div><span><font color=3D"#888888">=
<div><div class=3D"h5">

<p></p>

-- <br>
You received this message because you are subscribed to the Google<br>
Groups &quot;mongodb-user&quot; group.<br></div></div>
To post to this group, send email to <a>mongod...@googlegroups.com</a><div =
class=3D"im"><br>
To unsubscribe from this group, send email to<br>
</div><a>mongodb-user...@<u></u>googlegroups.com</a><div class=3D"im"><br>
See also the IRC channel -- <a href=3D"http://freenode.net#mongodb" target=
=3D"_blank">freenode.net#mongodb</a><br>
</div></font></span></blockquote></div><div class=3D"im"><br><br clear=3D"a=
ll"><div><br></div>-- <br>Atte.<br>Jorge Puente Sarr=EDn.<br>
</div></blockquote></div><div class=3D"HOEnZb"><div class=3D"h5">

<p></p>

-- <br>
You received this message because you are subscribed to the Google<br>
Groups &quot;mongodb-user&quot; group.<br>
To post to this group, send email to <a href=3D"mailto:mongodb-user@googleg=
roups.com" target=3D"_blank">mongodb-user@googlegroups.com</a><br>
To unsubscribe from this group, send email to<br>
<a href=3D"mailto:mongodb-user%2Bunsubscribe@googlegroups.com" target=3D"_b=
lank">mongodb-user+unsubscribe@googlegroups.com</a><br>
See also the IRC channel -- <a href=3D"http://freenode.net#mongodb" target=
=3D"_blank">freenode.net#mongodb</a><br>
</div></div></blockquote></div><br><br clear=3D"all"><div><br></div>-- <br>=
Atte.<br>Jorge Puente Sarr=EDn.<br>

<p></p>

-- <br />
You received this message because you are subscribed to the Google<br />
Groups &quot;mongodb-user&quot; group.<br />
To post to this group, send email to mongodb-user@googlegroups.com<br />
To unsubscribe from this group, send email to<br />
mongodb-user+unsubscribe@googlegroups.com<br />
See also the IRC channel -- freenode.net#mongodb<br />

--14dae9340469edd79904c90ff247--
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>date-sent</key>
	<real>1346970203</real>
	<key>flags</key>
	<integer>8590195712</integer>
	<key>original-mailbox</key>
	<string>imap://norberto%4010gen.com@imap.gmail.com/mongodb-user</string>
	<key>remote-id</key>
	<string>1880</string>
	<key>subject</key>
	<string>Re: [mongodb-user] Re: [pymongo-motor] OperationFailure on insert</string>
</dict>
</plist>
